name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: python app.py test

  Dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t flask:latest .

  deploy:
    needs: Dockerize
    runs-on: ubuntu-latest
    steps:
      - run: docker run -d -p 9000:5000 flask:latest

  caching:
    needs: [build, Dockerize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: requirements.txt
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

  automation-tests:
    needs: [build, Dockerize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: python app.py test
